### PR TITLE
add `bright` switcher to generate bright color theme

### PR DESCRIPTION
**Pull request by artur-shaik**
Hi. I made some sketch implementation of my issue #42.
Here is I add additional switcher `-b` for bright.
With switcher I reverse generated colors, so I can have bright backgound.
Here is example for:  https://alpha.wallhaven.cc/wallpaper/375647
screenshot_20170308_201422

### CODE REVIEW

**Comment by s-ol** [comment]
Looks pretty good, I will try it out at home.

If you call it a 'sketch' implementation, what do you think should happen before this is ready?

**Comment by artur-shaik** [comment]
In the begining I wanted to make it like a switcher when you activate theme, not generate. But looks like  it would be little bit tricker. 
So, for now I decided to add switcher to `generate` action.
May be we can generate two colorthemes (dark and light) from single color source for single theme, and then switch bright or dark, on activation.

**Comment by s-ol** [comment]
Color generation happens before templating, so there won't be a dark/light option for `themer activate`.

You could swap the colors in the normal/light palettes, but I don't think thats gonna yield great colorschemes either.

**Comment by artur-shaik** [comment]
Yeah, I see. Ok. I think I can do on the go switch of bright/dark themes with some wrapper scripts.

So, if you are ok with this PR, you can merge it.

**Pull request merged**
