### PR TITLE
fix ColorParser errors

### PR DESCRIPTION
**Pull request by morteza25**
Fixed some random behaviors on different input images.
I got this error: ValueError: invalid literal for int() with base 16: '' for one of your files "dotfiles/themer/.config/themer/dark/wallpaper.png"
Also faced this:
ValueError: Unknown format code 'X' for object of type 'float'

### CODE REVIEW

**Comment by sadjad** [comment]
This is the best fix I've ever seen on Github.

**Comment by coxley** [comment]
This overlaps with #59 and @s-ol decided to bucket it in with other bug fixes he's working on

**Comment by s-ol** [comment]
Sorry for the delays and thank you everybody for reporting and fixing these things. 1.8.2 is in AUR and PyPi, testing appreciated.

**Comment by coxley** [comment]
:+1:  :)

**Pull request merged**
