### PR TITLE
VimColorParser

### PR DESCRIPTION
**Pull request by s-ol**

### CODE REVIEW

**Comment by s-ol** [comment]
I have squashed the commits to keep history clean. Can you approve that everything is working as expected now, @97-109-107?

**Comment by 97-109-107** [comment]
Not sure what are you referring to by saying 

> Please fix this 

Just tested `pull-18` with both a `.vim` file and a `xresources` file. Both parsed correctly.

**Comment by s-ol** [comment]
See the line I commented on (_Changes_ tab on gitbub) - I got errors when parsing `solarized.vim` for example.

**Comment by 97-109-107** [comment]
Thanks, I missed that tiny icon.

I believe that the matter is more complicated than just handling unknown names. A theme like `solarized.vim` is more complicated that a _plain/non-compilable_ colorscheme like, let's say, [`lucario`](https://github.com/raphamorim/lucario/blob/master/vim/colors/lucario.vim).

A _plain_ `.vim` scheme has assignments like just like these:

`
hi Number ctermfg=177 ctermbg=NONE cterm=NONE guifg=#ca94ff guibg=NONE gui=NONE
`

Where all the color properties are provided for each `hi` group as hex or as the internal vim name of the color. That, I hope, is now handled by this commit.

As for the more demanding themes, they use conditional definitions like these (taken from `gruvbox`):

```
if s:is_dark
    let s:gb.dark0  = ['282828', 235]     " 40-40-40
```

These compile the actual highlight group definitions runtime. One can extract these compiled values from within vim by using [`:hi`](http://vimdoc.sourceforge.net/htmldoc/syntax.html#:highlight). I'm planning on doing a wrapper around that soon, but wouldn't that be out of the scope of themer?

**Comment by s-ol** [comment]
What commit are you referring to? I dont see any new ones in 97-109-107/themer. Maybe your forgot to push your changes?

If there is no feasible way of doing it, then it's fine like this of course. But it would be great if there was a graceful exit with a nice error message... though now that I think of it that should probably be handled within themer itself at the time of parsing templates.

**Comment by 97-109-107** [comment]
When I said

> That, I hope, is now handled by this commit

I was misleadingly referring to the state of `pull-18` right now. Sorry, I meant that _that's how it works right now_

**Comment by s-ol** [comment]
Oh, I see. I guess it is safe to merge now then.

**Pull request merged**
